### ISSUE TITLE
JCenter shutdown impact on Gradle builds

### ISSUE THREAD

**Issue by lennyqebian** [rechnerherz/aoprofiling-spring-boot-starter#1]
JCenter repository will be shut down in February 2022, with all of its packages:

https://laptrinhx.com/jcenter-shutdown-impact-on-gradle-builds-1941421215/

https://youtrack.jetbrains.com/issue/IDEA-264960

The related Maven / Gradle package to this project should be moved from JCenter to the **Maven Central** repository:

https://mvnrepository.com/artifact/at.rechnerherz/aoprofiling

![image](https://user-images.githubusercontent.com/5828527/117845904-927c3300-b246-11eb-8821-e780dc94a105.png)

**Comment by darioseidl** [comment]
Thank you for the heads up. I will move the artifact to Maven Central.

**Comment by darioseidl** [comment]
The 1.0.0 artifacts are now published on Maven Central. Future releases will also be published there instead of jcenter.
